### ISSUE TITLE
Una pregunta al día en tu correo electrónico

### ISSUE THREAD

**Issue by omiras** [IronHack-2024/CodeQuestAPI#17]
## Análisis

Queremos permitir que los usuarios se suscriban a nuestra newsletter para enviarles cada día una pregunta tipo test sobre programación.
En la vista principal "/" vamos a generar una caja de texto para poder introducir el email. 
![Image](https://github.com/user-attachments/assets/d644646e-0aa4-4566-92e8-a8a06c5b5e7d)

El usuario escribe su email y debemos registrarlo en nuestro sistema.

## Opción 1

Mirar el servicio de _mailchimp_ para ver de que manera nos puede ayudar a realizar esta tarea

## Opción 2

Guardar en una de colección de usuarios el correo de cada persona (problemas protección de datos? comprobar)
Tendriamos que tener una modelo nuevo para los usaurios.
Con NodeJS y nodemailer (módulo de terceros) se puede configurar el envío periódico de emails.

Cualquier las dos opciones lo que hay que hacer es
- GET a nuestro endpoint para obtener una pregunta tipo test random (de momento)
- Maquetar el email (supongo que mailchimp ofrecerá herramientas de desarrollador para hacer esto)
- Enviar el correo una vez por semana

## Criterios de aceptación

- [ ] Existe un cuadro de texto en "/" para poder introducir nuestro email y subscribirnos
- [ ] Al hacer click en el botón de "Subsribe" confirmamos la subscripción (mediante un mensaje informativo en la vista o a traves de mailchimp.com)
- [ ] Forzar el envio de un email para comprobar que este recibe una pregunta tipo test indicando cuál es la opción correcta

**Comment by omiras** [comment]
@crimanlor Puede asesorar sobre el uso de plantillas en mailchimp ya que usa una herramienta similar en el trabajo

**Comment by omiras** [comment]
!Hola! He estado explorando un poco esto y parece un pelín difícil, pero quizás podéis explorar estos puntos

1. La idea es que mailchimp almacene el correo de todas las personas que se quieran subscribir. Porque ellos entiendo que pueden cumplir con la RGPD y también gestionar facilmente el _unsubscribe_
2. En una primera versión de la funcionalidad a lo mejor simplemente tenemos que permitir que una persona pueda introducir su email en nuestro formulario y se registre en mailchimp. Luego manualmente creamos un email con la pregunta tipo test y lo actualizamos cada semana.
3. Existe un cliente en [NodeJS](https://github.com/mailchimp/mailchimp-marketing-node/) para gestionar la base de datos de email de mailchimp. También parece que des de ahí se puede modificar el _template_ del correo 
![Image](https://github.com/user-attachments/assets/dbef36a5-3182-47fa-b4c3-de6863398364)

4. Supongo que la versión extendida de esta funcionalidad podría ser que, cada cierto tiempo, modificar el _template_ de mailchimp con una pregunta tipo test nueva procedente de nuestra base de datos. 

¡Todo un reto @MariaChmielinska @evahuertas! Pero parce muy divertido 💃🏻 
Vamos viendo, comentamos los progresos.

**Comment by evahuertas** [comment]
![Sin título-2024-10-31-1908](https://github.com/user-attachments/assets/84f467e0-a8c3-4085-9d61-7ff10455b6f5)
Esquema hecho en excalidraw con un **mapa mental de nuestra aplicación** y qué parte corresponde a esta issue de subscripción a newsletter.
Esto nos servirá para decidir si utilizamos **servicio de terceros** (**[mailchimp](https://github.com/mailchimp/mailchimp-marketing-node/)**) **o** **crearemos un servicio con un módulo de terceros** de node (**[Node Mailer](https://mailtrap.io/blog/sending-emails-with-nodemailer/#How-to-send-emails-with-Nodemailer)**).

**Comment by MariaChmielinska** [comment]
Update 4 NOV:
1. Creado cuenta en Mailchimp:  
codequestapi@gmail.com
pw: ###
API Key: ##
server: us-22
Contact List ID: 58371aa183

2. creado view/endpoint `/subscribe` con un formulario para subscribir. (cambiarlo a Home?)
3. instalado @mailchimp/mailchimp_marketing (paquete de tercero).
4. template creado en Mailchimp y probado con un email test enviado a nuevo subsciber. La email contiene la opción de unsubscribe.

**Comment by omiras** [comment]
test

**Comment by omiras** [comment]
test2

**Comment by MariaChmielinska** [comment]
Update 10th Nov:

1. successfull fetch of audience/contacts from mailchimp (app.js)
2. installed nodemailer and created email template (emailtemplate.html)
3. BLOCKER: sendEmails(); returns error:   code: 'EAUTH',
  response: '535-5.7.8 Username and Password not accepted. For more information, go to\n' +
    '535 5.7.8  https://support.google.com/mail/?p=BadCredentials ffacd0b85a97d-381ed99790csm11362770f8f.46 - gsmtp',
  responseCode: 535,
  command: 'AUTH PLAIN'
Apparantly Gmail needs a better Authorization for less secure apps. 
Status: searching for solution.

BLOCKER Solved 11th Nov with APP Password creation for GMAIL.

Update 11.Nov: 
1. created get` '/sendEmails' `to execute the send out of emailtemplate.js file with fetch of audience&contacts from Mailchimp-> works but all in app.js file
2.  emailtemplate.js modified to inline css style.

TODO: 
1. dynamic insert of `getRandomQuestion `into emailtemplate.js
2. Cron function for node.js to schedule email send out

**Comment by omiras** [comment]
Thanks for the update @MariaChmielinska 
  
> * installed nodemailer and created email template (emailtemplate.html)

Good start!

> Apparantly Gmail needs a better Authorization for less secure apps.

Gmail's policy has been changing over time, so that may be the case now.


In case it helps, in 2021 we worked on a project that used Nodemailer with Gmail. You can take a look [here](https://github.com/FOAP-Netmind-2021/avisa-me/tree/main/utils), as it might provide a dynamic template for the email along with some configuration help..

**Comment by kevmhughes** [comment]
Despite taking the first step of integrating this functionality into the main branch, there are still some things to resolve/finish:

- the cron job should be moved outside of the GET request `getSendEmails` so that the GET request can resolve and not have to wait for the execution of the cron job, and to avoid the possibility of repeatedly calling the cron job. It should be done only once when initiating the app
- consider using flash middleware to send success/error messages to the user after submitting an email address to the subscription list
- make code Prettier
- remove console.logs

**Comment by kevmhughes** [comment]
### HOW TO TEST THIS FEATURE

### Run the Code Locally:

**Clone the Repository:**
`git clone https://github.com/IronHack-2024/CodeQuestAPI.git`
`cd codeQuestAPI`

**Checkout the Following Branch:**
`git checkout fix/17-newsletters`

**Install Dependencies:**
`npm install`

**Set The Environment Variables:**
Create a `.env` file in the root directory.

Add the following environment variables to `.env`:
MONGODB_URI=<YOUR_MONGODB_URI>
API_KEY=<GOOGLE_GENERATIVE_AI_API_KEY>
MAILCHIMPKEY=<MAILCHIMP_API_KEY>
LIST_ID=<MAILCHIMP_LIST_ID>
APP_PASSWORD=<NODEMAILER_PASSWORD>

**Start the project:**
`npm run dev`

### Testing the subscribe functionality:
Given that the endpoint `/subscribe` is only used to handle the subscription logic, does not have a dedicated view and resolves by redirecting to `/`, we will **NOT** test the endpoint with Thunder Client or a similar API testing tool. We will test it directly on the home page of the app. 

Go to `http://localhost:3000/`* 
<sub>*Use the Google Chrome browser: some browsers may have undesired behaviour due to CSS Tailwind settings in development mode.<sub>

Scroll to the bottom of the screen and add your personal email to the form input with the following id: `email`.

http://localhost:3000/
<img width="1436" alt="home" src="https://github.com/user-attachments/assets/23bb8ee1-2edb-4d86-988d-4b9cad689018">

Press enter to submit the email.* 
<sub>*the form submit button/text color is not visible in this branch, the UI of the form will be updated later in another issue.<sub>

Check the console for a success message with the following format `Successfully added contact for the weekly question. ID: e16ca81c51ff4251be991e018214eaa5`:

Success message:
<img width="1000" alt="Screenshot 2024-11-24 at 12 55 50" src="https://github.com/user-attachments/assets/4cbd9462-21d9-4bd2-899b-7dd6601829d7">

### See the list of subscribers:
If you want to see a list of the first 100 subscribers' emails from the Mailchimp database, add  `line 47` and `line 55` to the code as can be seen in the image below:
<img width="1277" alt="Screenshot 2024-11-25 at 15 15 31" src="https://github.com/user-attachments/assets/fa915b02-c791-40ca-8c2b-6915b39faddf">

On restarting the app you will see a list of current subscribers:
<img width="1277" alt="Screenshot 2024-11-25 at 15 13 47" src="https://github.com/user-attachments/assets/a7b53db8-cb35-4e58-9ee7-dd8370a6b8bb">

### Testing the newsletter functionality:

**AVOID SENDING EMAILS TO THE SUBSCRIBERS MORE THAN ONCE!***
<sub>*After following the instructions below, wait for one minute until you see the console log which states that the emails were sent successfully, then kill the terminal or return the cron schedule to its original settings to avoid sending emails every minute!<sub>

Open `utils/cron.js` and modify the cron schedule as below. 

You should only modify this part of the code: `cron.schedule("0 8 * * 3", ...`
  
Before modification, your cron schedule will look like this:
<img width="888" alt="before" src="https://github.com/user-attachments/assets/0358eb86-5c01-43d4-95c1-60b1c71a2912">

  
After modification, it should look like this:
<img width="888" alt="after" src="https://github.com/user-attachments/assets/b69f14ed-f51d-4668-9368-85837051a3bf">

Wait one minute until you see the the following in the console `Emails have been sent successfully.`.

success message:
<img width="978" alt="email sent" src="https://github.com/user-attachments/assets/79d1ced7-357f-49a2-8600-f9a534996c91">

If you would like to see the actual newsletter, go to the email address that you submitted with the form and check your inbox for an email from the CodeQuestApi with the following title: Welcome to Our Weekly Code Quest!. You should see a newsletter similar to the one below.

Newsletter (mobile view):
<img width="600" alt="email" src="https://github.com/user-attachments/assets/9893b7ba-1ebe-47ae-8236-8181470e8c22">
